### ISSUE TITLE
Highlight search results

### ISSUE THREAD

**Issue by miwurster** [JabRef/cloudref#12]
![image](https://user-images.githubusercontent.com/2610997/33476684-22fb3b9a-d683-11e7-8869-138fcc635b5f.png)

See an example:
![image](https://user-images.githubusercontent.com/2610997/33476713-3ec43872-d683-11e7-8fa1-48b57857fd85.png)

**Comment by luko0610** [comment]
Hello, if this is still available I'd like to take it.

**Comment by koppor** [comment]
Sure, go ahead!

**Comment by luko0610** [comment]
I'm having an issue setting up the project. I cannot login, altough I created the sqlite file under the user.home directory.

**Comment by luko0610** [comment]
Okay, I got it to work.

**Comment by koppor** [comment]
No login issue is described at https://github.com/JabRef/cloudref/issues/24. Maybe, you can support there, too.

**Comment by luko0610** [comment]
I'll look into it once I'm back home.

**Comment by luko0610** [comment]
@koppor 
Hello,
So I ran into a small issue and need some advice.
My approach is to insert a html <mark></mark> tag directly into the references array, which works perfect if you only search once. The problem is because I am directly altering the data, the <mark> added from the previous search will still be there. So I need to find a way to create a backup of the references array before altering it, which I can then use to restore the references before the next search.

1st search (works perfectly)
![1](https://user-images.githubusercontent.com/24602363/67148691-9500eb80-f2a2-11e9-99eb-b702c96511d7.png)
2nd search (still having the markup from the 1st search)
![2](https://user-images.githubusercontent.com/24602363/67148692-9500eb80-f2a2-11e9-96e3-7424f218a2ee.png)

**Comment by koppor** [comment]
I think, the reference should have an attribute "searchResultHit" (boolean). If true, the CSS class "highlighted" is applied. This CSS class implements some sort of highlighting. - At the beginning of a search. `searchResultHit` is cleared.

**Comment by luko0610** [comment]
Yes, because we do not want to highlight the whole text we need to actually insert a html tag around the part of the text we want to highlight.

**Comment by koppor** [comment]
Oh, I see.

Did you check https://angular.de/artikel/mark-highlight-search-results/ and https://stackoverflow.com/a/52569482/873282 and https://stackoverflow.com/a/46106843/873282. These came out here when I googled `angular highlight search result`. Did they work? If not, please start creating an [ADR](https://adr.github.io/madr/) in `docs/adr`.

**Comment by luko0610** [comment]
Thanks for your response. First link looks promising. Haven't been thinking about that approch. I'll try it out tomorrow.

**Comment by tobiasdiez** [comment]
There is also markjs if you want to highlight on the client side

**Comment by luko0610** [comment]
Okay, I finished it and made a pull request. Solving this using a custom pipe was way easier than I thought.
